import {
  DEFAULT_PAGE_EDITOR_TEXT,
  LEGACY_COMPONENT_TAG_REGEX,
  PAGE_COMPONENT_TOKEN_REGEX,
} from "@/lib/pageDocument";

export const INITIAL_TEXT = DEFAULT_PAGE_EDITOR_TEXT;
export const COMPONENT_TAG_REGEX = LEGACY_COMPONENT_TAG_REGEX;
export const COMPONENT_TOKEN_REGEX = PAGE_COMPONENT_TOKEN_REGEX;
