import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "./lib/components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-dvh h-auto w-screen flex items-start justify-start">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
