import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./globals.css";
import { Sidebar } from "./lib/components/sidebar/Sidebar";
import { Chat } from "./lib/components/chat/Chat";
import { SIDEBAR_COOKIE, CHAT_COOKIE } from "./lib/cookies";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sidebarValue = cookieStore.get(SIDEBAR_COOKIE)?.value;
  const chatValue = cookieStore.get(CHAT_COOKIE)?.value;
  const initialSidebarOpen = sidebarValue != null ? sidebarValue === "true" : undefined;
  const initialChatOpen = chatValue != null ? chatValue === "true" : undefined;

  return (
    <html lang="en">
      <body className="antialiased min-h-dvh h-auto w-screen flex items-start justify-start">
        <Sidebar initialSidebarOpen={initialSidebarOpen} />
        <div className="w-full">{children}</div>
        <Chat initialChatOpen={initialChatOpen} />
      </body>
    </html>
  );
}
